### ISSUE TITLE
Change default git branch

### ISSUE THREAD

**Issue by mhoofman** [thoughtworks/cruisecontrol.rb#104]
I'm attempting to change a project's default git branch from what was originally set up. Currently its building from the git project's master branch. I would like to change it to "development".

I added the following line in `.cruise/projects/my_project/cruise_config.rb`:

``` ruby
project.source_control = SourceControl::Git.new :branch => "development"
```

After a restart and new build it continues to source from the master branch.

Is there some other configuration needed that I'm missing?

**Comment by matteograndi** [comment]
Hi, now me too have the some problem.

Have you fixed that problem, now?

**Comment by mhoofman** [comment]
I was not able to fix this issue. I moved to an alternative CI.

**Comment by matteograndi** [comment]
Me too.

But I saw that you can resolve the matter by declaring the program via shell by adding the option -b or --branch instead of on the dashboard

**Comment by seanmarcia** [comment]
Sorry for the slow response, I only recently got access to the project and with the help of a few others are in the process of triage. Since it has been so long I'm closing this but if this is still an issue let me know!
