### ISSUE TITLE
Builder doesn't understand parameterized rake tasks

### ISSUE THREAD

**Issue by todd-a-jacobs** [thoughtworks/cruisecontrol.rb#105]
I'm currently using CruiseControl.rb from source, where HEAD is currently SHA: 422b3ee1dc08e7512e3a11dac4324545b413d819. This may or may not matter to the issue, but it's worth knowing that it's present in HEAD, and not some legacy version.

Given a project-specific **cruise_config.rb** file as follows:

```
Project.configure do |project|
  project.environment['RAILS_ENV'] = 'test'
  project.rake_task = 'cruise["marketing"]'
end
```

The builder will fail, and the following entry placed into the builder.log:

> Custom rake task(s) 'cruise["marketing"]' not defined

However, I can run `bundle exec rake cruise["marketing"]` from the command line without problems. So, rake doesn't think it's a problem, but the CruiseControl.rb builder does.

It seems to me that passing parameters to a rake task is common enough that it _should_ work, but clearly it doesn't. Am I doing something wrong here, or is the builder simply unable to grok a parameterized rake task as legal syntax?

**Comment by seanmarcia** [comment]
Sorry for the slow response, I only recently got access to the project and with the help of a few others are in the process of triage. Since it has been so long I'm closing this but if this is still an issue let me know!
