### ISSUE TITLE
Email notification sent when test is still running

### ISSUE THREAD

**Issue by jacob-carlborg** [thoughtworks/cruisecontrol.rb#107]
I get an email notification saying that the test failed even though the test is still running.  It happens regardless if the test later passes or fails. I'm using 422b3ee1dc.

**Comment by seanmarcia** [comment]
Sorry for the slow response, I only recently got access to the project. Since it has been so long I'm closing this but if this is still an issue let me know!

**Comment by jacob-carlborg** [comment]
I have not hit this issue in a long time. Hopefully gone :smiley:
