### ISSUE TITLE
site_config.rb seems to be ignored

### ISSUE THREAD

**Issue by jacob-carlborg** [thoughtworks/cruisecontrol.rb#108]
The settings I put in `site_config.rb` don't seem to have any effect. For example, `ActionMailer::Base.smtp_settings` and `Configuration.dashboard_url` don't have any effect. Although if I put `ActionMailer::Base.smtp_settings` in the `cruise_config.rb` file in the repository it works.

**Comment by seanmarcia** [comment]
Sorry for the slow response, I only recently got access to the project. Since it has been so long I'm closing this but if this is still an issue let me know!

**Comment by jacob-carlborg** [comment]
Seems it's working.
