### ISSUE TITLE
Nil error with empty commit messages

### ISSUE THREAD

**Issue by stuzart** [thoughtworks/cruisecontrol.rb#111]
Using mercurial, there was a commit with an empty commit message. This led to the error:
[error] undefined method `[]' for nil:NilClass
[error]   /srv/rails/cruisecontrol/lib/source_control/mercurial/log_parser.rb:41:in`parse_for_message'
[error]   /srv/rails/cruisecontrol/lib/source_control/mercurial/log_parser.rb:17:in `parse'
[error]   /srv/rails/cruisecontrol/lib/source_control/mercurial/log_parser.rb:13:in`each'
[error]   /srv/rails/cruisecontrol/lib/source_control/mercurial/log_parser.rb:13:in `parse'
[error]   /srv/rails/cruisecontrol/lib/source_control/mercurial.rb:74:in`revisions_since'
[error]   /srv/rails/cruisecontrol/lib/source_control/mercurial.rb:69:in `new_revisions'
[error]   /srv/rails/cruisecontrol/lib/source_control/mercurial.rb:54:in`up_to_date?'
[error]   /srv/rails/cruisecontrol/app/models/change_in_source_control_trigger.rb:14:in `build_necessary?'

I fixed this on my own version by updating the method to:
def parse_for_message(message)
        matches = message.match(/^description:\s_(._)/)
        if matches.nil?
          "none"
        else
           matches[1]
        end
end

**Comment by seanmarcia** [comment]
Sorry for the slow response, I only recently got access to the project. Since it has been so long I'm closing this but if this is still an issue let me know!
