### ISSUE TITLE
Download links broken, there's nowhere to download the project from anymore.

### ISSUE THREAD

**Issue by wellinformed** [thoughtworks/cruisecontrol.rb#113]
Link from http://cruisecontrolrb.thoughtworks.com to https://github.com/thoughtworks/cruisecontrol.rb/downloads shows that "There aren't any uploads for this repository".

**Comment by jdickey** [comment]
Five days; no reply and no action on this? Wow. Just wow.

**Comment by matteograndi** [comment]
see this link https://github.com/thoughtworks/cruisecontrol.rb cut the 'downloads' part

**Comment by bguthrie** [comment]
To the best of my knowledge the project is no longer actively maintained.

**Comment by seanmarcia** [comment]
Fixed
