### ISSUE TITLE
r1.9 - [error] invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by pschyska** [thoughtworks/cruisecontrol.rb#12]
I'm getting  invalid byte sequence in US-ASCII which is a sign for missing magic encoding comment in some source file. unfortunateley i can't see the stack trace to i dont know which file it is.
There should be a line 
    # -_\- encoding : utf-8 -_-
as the first line in every source file as a requirement for ruby-1.9.

Thanks,

Paul

**Comment by bguthrie** [comment]
I've been poking around and I can't replicate this. Also, I haven't been able to find any background on the encoding requirement in Ruby 1.9. I'm using 1.9 to run CC.rb locally and I haven't run into any trouble with it - can you still replicate the problem?

**Comment by betarelease** [comment]
We should close this cause according to Yehuda Katz (http://yehudakatz.com/2010/05/17/encodings-unabridged/)
"When using Rails 3.0 with Ruby 1.9.2-final, you will generally not have to care about encodings."

Which is why you are able to reproduce the problem either.

**Comment by bguthrie** [comment]
Ahh, I didn't see that article before. Thanks for the heads up, Sudhindra. Closing this one out.
