### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by epinault** [thoughtworks/cruisecontrol.rb#134]
1) I noticed the download link from docs and thoughtwork website points to a link with no download

try

https://github.com/thoughtworks/cruisecontrol.rb/downloads

2) What is the state of this project? Is this still active or is this dead?

**Comment by vizcay** [comment]
+1 What is the state of this project? Is this still active or is this dead?

**Comment by alexeyv** [comment]
As far as I understand, it's dead. 

I was heavily involved back in 2010, but nowadays I just default to TeamCity. It has a free license option that's plenty good enough for everything CC.rb was good for back in the day. It's not the only alternative either, just the most obvious and highly polished one.

**Comment by jdickey** [comment]
I, too, am sad to see cruisecontrol.rb die, but have accepted reality and moved on. Whether you prefer a local tool like TeamCity per @alexeyv, or a hosted solution like CodeShip (which I use and love), CircleCI or Travis, it's a commodity bit of infrastructure now — a far different world from when cc.rb was the bee's knees.

**Comment by epinault** [comment]
how sad. Was like a simple solution that works great for simple rails/ruby project. Thanks for the update
