### ISSUE TITLE
FAILED: uninitialized constant RAILS_ROOT

### ISSUE THREAD

**Issue by austinthecoder** [thoughtworks/cruisecontrol.rb#16]
I get that error when running:

./cruise add owl -r repo -s git

from the master branch of cruisecontrol.rb

**Comment by bguthrie** [comment]
Thanks for the bug report; don't know how I missed this in the initial sweep. It's been fixed in 094ed66860e05ccdbc1f5d7251230c8c44b8b94d. If you get a chance, please test it and confirm the fix.
