### ISSUE TITLE
not all errors are displayed on build page

### ISSUE THREAD

**Issue by aabdalla** [thoughtworks/cruisecontrol.rb#23]
One of the most valuable features of CruiseControl is the ability to get a snapshot of a build. If only some errors are visible sometimes, we lose some of the core value.

**Comment by aabdalla** [comment]
This happens because the errors are displayed as a consequence of looking at only the displayed build.log content which is a truncated version of the actual build.log. If errors reside in the truncated portion of the build log they are never displayed on the build page.

**Comment by owenbyrne** [comment]
I had a bit of a dig on this, then I checked the closed issues and realised it's been dealt with (serves me right for not checking for dupes first!): https://github.com/thoughtworks/cruisecontrol.rb/pull/24

Anyway, I think it might be worth amending the text we display to the user to be a bit more explicit in letting them know they might be missing out on some useful stuff.

```
diff --git app/views/builds/show.html.erb app/views/builds/show.html.erb
index cd24e57..d9491a9 100644
--- app/views/builds/show.html.erb
+++ app/views/builds/show.html.erb
@@ -70,12 +70,11 @@
           <a name="build_log"></a>
           <% if @build.output_exceeds_max_file_display_length? %>
           <p>
-              The size of the file you're viewing now is <%= number_to_human_size(@build.build_log.size) %>, which is too big to display in the dashboard;
-              CC.rb is configured to truncate any files longer than <%= number_to_human_size(Configuration.max_file_display_length) %>. 
-              You can override this value in <code>site_config.rb</code> by setting <code>max_file_display_length</code>
-              to your desired value in bytes (e.g. <code>50.kilobytes</code>), or <code>nil</code> to allow files of any length.
+              The size of the file you're viewing now is <%= number_to_human_size(@build.build_log.size) %>, which is too big to display in the dashboard;
+              CC.rb is configured to truncate any files longer than <%= number_to_human_size(Configuration.max_file_display_length) %> which may mean useful information such as errors and warnings are not being displayed. 
+              You can override this value in <code>site_config.rb</code> by setting <code>max_file_display_length</code>
+              to your desired value in bytes (e.g. <code>50.kilobytes</code>), or <code>nil</code> to allow files of any length.  Note that this may impede performance.
           </p>
-
           <p>File path: <code><%= @build.build_log.expand_path %></code><br/></p>
           <% end %>
```

**Comment by seanmarcia** [comment]
Sorry for the slow response, I only recently got access to the project and with the help of a few others are in the process of triage. Since it has been so long I'm closing this but if this is still an issue let me know!
