### ISSUE TITLE
Your build is broken

### ISSUE THREAD

**Issue by cflipse** [thoughtworks/cruisecontrol.rb#28]
http://cruisecontrolrb.thoughtworks.com/builds/CruiseControlRB

And has been since April 27th, almost a month.

**Comment by bguthrie** [comment]
Thanks for the heads up. I'm aware it's been broken since the upgrade and for various reasons I haven't been able to get access until fairly recently to the system that hosts that server. Expect a fix soon.

**Comment by bguthrie** [comment]
Attempted a fix today but the box it's running on is ancient and we had some trouble, and ThoughtWorks IS is recommending (and I agree) that we should replace it. New server is getting provisioned tomorrow. In the meantime, I'll work on ensuring that CC.rb is still daemonizable.

**Comment by bguthrie** [comment]
Build is currently passing at http://cruisecontrolrb.thoughtworks.com/builds/CruiseControl, thanks to @ketan (for the fix that pushed it into green) and @ranjibd and @ajeygore for the environment setup.
