### ISSUE TITLE
Download build.log if build log is too long

### ISSUE THREAD

**Issue by andhapp** [thoughtworks/cruisecontrol.rb#3]
A very big build log is sensibly truncated and not displayed in the dashboard. In such a circumstance, I should be able to just download the build.log on my local machine and inspect it for problems since not all the test/errors and failures are displayed in the dashboard for some reason.

**Comment by vraravam** [comment]
Just providing a link to the build log file just renders it as text without any truncating - this is what we use on our current project.

**Comment by andhapp** [comment]
@vraravam - Exactly. I was going to create a patch for the same but decided to enquire what others were doing. Thanks.

**Comment by iconnor** [comment]
@vraravam I like the idea of a direct link in the email - if you make a patch, I will be happy to test - thanks.

**Comment by vraravam** [comment]
Sorry - I am on a Java project - and am not using ccrb right now. So my turn-around time would be a little high.

**Comment by iconnor** [comment]
It looks like there is already a link to the failure but just need to add '/build.log' to the end in an additional link. Do you know where this code lives? It did not look to be as easy as just changing the mail template.

**Comment by andhapp** [comment]
I would love to help but I am tied up with other projects and I don't use ccrb anymore. I am using Jenkins (Hudson).

**Comment by betarelease** [comment]
I found three locations - and I dont know which one @iconnor you are talking about but here it goes
- build.rb
  def contents_for_display(file)
- show.html.erb
     <div class="section_content"><div class="logfile"><%= format_build_log(@build.output) %></div><div><%= link_to "See unformatted build log&hellip;".html_safe, build_artifact_path(:project => @project.name, :build => @build.label, :path => 'build.log') 
- build_report.html.erb

<%= @build.output %>

---

May be its just a matter of adding the same code as in show.html.erb to the build_report file and you will have the correct link to download the text build.log file.

( I am new to the codebase so just sharing what I found while exploring.)

**Comment by srushti** [comment]
You should take a look at #23 (and its pull request #24). It's an attempt to make sure the errors, at least, are displayed regardless of the length of the build log. That might serve your needs until this issue is addressed specifically.

**Comment by bguthrie** [comment]
I'm currently evaluating that solution. I'm not yet convinced that allowing CC.rb to parse the entire file is a wise idea but am happy to accept the patch if others believe that this is a reasonable fix.
