### ISSUE TITLE
Ensure JRuby Compatibility

### ISSUE THREAD

**Issue by bguthrie** [thoughtworks/cruisecontrol.rb#32]
CC.rb should function correctly on Ruby 1.9 and Rails 3 on Windows, which is to say:
- backwards-compatible with existing site and project configs
- installable and runnable via a jar
- starts and stops builders and builds projects
- compatible across Mac, Linux, Windows platforms

**Comment by ketan** [comment]
Tests are green as of rev 0eebf5a3e3512131bc6a. The server seems to run fine using jetty and as a standalone jar.

Marking as closed. I'll open more specific issues around running the individual scripts from the jar later.
