### ISSUE TITLE
Fix documentation at thoughtworks.github.com/cruisecontrol.rb

### ISSUE THREAD

**Issue by bguthrie** [thoughtworks/cruisecontrol.rb#42]
Either get the documentation statically generated so we can place it there or put a redirect in place that points to cruisecontrolrb.thoughtworks.com.

**Comment by spritle** [comment]
1+ 
Please fix documentation

**Comment by ask4prasath** [comment]
+1 Down for longtime

**Comment by ketan** [comment]
The documentation on the website is fixed; as such I'd like to mark this as closed.

Would people still prefer some form of static documentation generation process?

**Comment by spritle** [comment]
We can close this issue.
