### ISSUE TITLE
Rails 3 upgrade breaks existing browser sessions

### ISSUE THREAD

**Issue by bguthrie** [thoughtworks/cruisecontrol.rb#44]
As reported by @alexeyv:

Rails session (cookie based, of course) from the older Rails version makes the newer Rails version blow up thus:

`ActionDispatch::Session::SessionRestoreError (Session contains objects whose class definition isn't available. Remember to require the classes for all objects kept in the session.
(Original exception: uninitialized constant ActionController::Flash::FlashHash [NameError])):
  lib/cruise_control/init.rb:49:in `start'
  lib/cruise_control/init.rb:46:in `tap'
  lib/cruise_control/init.rb:46:in `start'
  lib/cruise_control/init.rb:12:in `send'
  lib/cruise_control/init.rb:12:in `run'`

**Comment by kpumuk** [comment]
To fix the problem just change one letter in `cookie_verification_secret.rb`

**Comment by bguthrie** [comment]
In other words, use a new token rather than re-using the old one? The one we're using was carried over as part of the upgrade to Rails 3 from its previous value.

**Comment by kpumuk** [comment]
Absolutely right. I just upgraded yesterday, and it helped

**Comment by kpumuk** [comment]
The reason it helps is Rails abandon session with invalid key
