### ISSUE TITLE
builds sidebar lost coloring 

### ISSUE THREAD

**Issue by ywen** [thoughtworks/cruisecontrol.rb#52]
in public/cruisecontrol.less, line #383. it specify the color of the text to be cruise-blue. 

```
  .build_link {
    a {
      display: block;
      padding: 6px 6px 6px 10px;
      color: @cruise-blue;
      border-right: 1px solid #bbb;

      &:hover {
        text-decoration: none;
        background-color: lighten(#ccc, 10%);
      }
    }
```

I believe in the older versions, when a build failed, the sidebar text is red, which is what I want. I couldn't just use customized site.css to override it using failed class because this overrides a.failed. The only solution seems to get rid of this line. 

Is there a reason you want it to be there? Thanks

**Comment by bguthrie** [comment]
I removed it because my subjective judgment was that it wasn't very visually attractive and the feedback that it provided above and beyond the word "failed" didn't justify keeping it, but I don't feel very strongly about that, and will consider bringing it back if enough people miss it.

**Comment by ywen** [comment]
I don't know. A word is always less visually "standing-out" than colors, at least for me. In a galance, red color is/should be more alarming than  "FAILED". This could be just me.

That being said, I think at least the css should give the users a chance to override this setting in site.css.
