### ISSUE TITLE
git changeset 

### ISSUE THREAD

**Issue by ywen** [thoughtworks/cruisecontrol.rb#53]
it gave me something like this:
     [SourceControl::Git::Revision:(bc2feba87882f81ad6f601ed72a7f241d3ac2c2f)]

instead of the files being changed, who changed etc.

the version is the current master.

Thanks

**Comment by bguthrie** [comment]
That's been happening for a while, and is a duplicate of https://github.com/thoughtworks/cruisecontrol.rb/issues/4, which is in the "to fix soon" bucket.
