### ISSUE TITLE
The demo app (cruise monitoring itself) is down

### ISSUE THREAD

**Issue by trcarden** [thoughtworks/cruisecontrol.rb#59]
Its pretty bad when the solution demo is busted: http://cruisecontrolrb.thoughtworks.com/projects

**Comment by bguthrie** [comment]
We've rebuilt the prod environment recently and it's not entirely stable yet. We'll take a look. Thanks for the bug report.

**Comment by bguthrie** [comment]
Fixed thanks to @ketan.
