### ISSUE TITLE
build in progress doesn't honor the 'dashboard_refresh_interval' config

### ISSUE THREAD

**Issue by aabdalla** [thoughtworks/cruisecontrol.rb#61]
In site_config.rb I set:

Configuration.dashboard_refresh_interval = 90.seconds

This is because our log files are kinda large and we can have many people looking at the build. When I'm looking at the build in progress it will always auto-refresh every 5 seconds even though. I realize the distinction between project & build but with the auto-refresh I can't scroll down or check out current failures without the page resetting.

**Comment by bguthrie** [comment]
@aabdalla, thanks for the patch. It's been merged, so I'll go ahead and close this out.
