### ISSUE TITLE
do_clean_checkout is broken

### ISSUE THREAD

**Issue by orenbenkiki** [thoughtworks/cruisecontrol.rb#64]
(There is a two-years-old ticket #270 with a proposed patch to fix it).

One would expect to be able to just set do_clean_checkout and be done; however this would result in the work directory disappearing and the web server refusing any page requests. There are workarounds, but the documentation doesn't mention any of them or even that this is an issue in the 1st place.

**Comment by bguthrie** [comment]
Will pull the patch in from the old Lighthouse ticket.

**Comment by bguthrie** [comment]
Apologies for the delay on this - personal life kept me from addressing it. Many thanks for the patch. Please let me know if doesn't look okay.
