### ISSUE TITLE
Installing latest version

### ISSUE THREAD

**Issue by scottillogical** [thoughtworks/cruisecontrol.rb#67]
I don't get it - the latest version in the downloads tab hasn't been updated since 2009. 

How are we supposed to a more recent version short of doing a git clone?

**Comment by bguthrie** [comment]
The master branch is being kept up to date but we haven't tagged a formal release in a while. The sticking point on my end is finding a way to package it as a gem that doesn't completely suck (issue #40). When I find one, we'll release. Until then, we're tracking milestone progress here: https://github.com/thoughtworks/cruisecontrol.rb/issues/milestones
