### ISSUE TITLE
Always have "Source Control Error"

### ISSUE THREAD

**Issue by mech** [thoughtworks/cruisecontrol.rb#70]
When I start CC using ./cruise start --daemon, my builder will run for the very first time. But after that I immediately got "Source Control Error" which suggest that it cannot git fetch origin, but when I do the command line inside, it can :(

[error] /Users/administrator/.cruise/projects/cp/work administrator$ git fetch origin
You don't exist, go away!
fatal: The remote end hung up unexpectedly

When I cd into the "work" directory and do a normal git fetch origin, I am not getting fatal error. However, trying to ./cruise stop (I am not sure if there is such thing) will make CC working again, but only for a while.

Previously my CC is all working fine.

**Comment by thewoolleyman** [comment]
This is probably related to using an incorrect SSH identity/key when accessing github.  

This can also be caused because you are proxying your ssh credentials via ssh-agent when you log in and start cruise interactively.

Solution is to make sure that the system has the correct github credentials in your administrator/.ssh/id_rsa - and ensure you aren't proxying any ssh credentials when you restart cruise.

**Comment by mech** [comment]
But why does it work the first time whenever I start CC, but then after that it did not work when interval come?

FYI, it work the very first time whenever I try to do ./cruise start or ./cruise stop, then it will wake up from its sleep and able to correctly get the my private git repo. After that it, the second time, it will not :(

Thanks for such a fast reply above :)

**Comment by mech** [comment]
When I look at the SourceControl::Git#load_new_changesets_from_origin, there is a comment on a lighthouse ticket on system_gem requirement (probably)

https://cruisecontrolrb.lighthouseapp.com/projects/9150-cruise-control-rb/tickets/229-sometimes-git-hangs

Still investigating.. hopefully will address :)

**Comment by mech** [comment]
Sori, that was not needed for Ruby 1.9. Please ignore previous comment.

**Comment by thewoolleyman** [comment]
Sorry, I don't have time to provide more specific instructions right now, but this seems like you are using the wrong github key for some reason.  The ssh-agent scenario I described is one possible cause for this which may not be apparent.  Look into how to disable ssh-agent on your server and client, and see if that helps.

**Comment by bguthrie** [comment]
@mech, any luck reproducing? Is it the same issue as in the Lighthouse ticket?

**Comment by mech** [comment]
@bguthrie, what I did is I remote in using Apple Remote Desktop to open a terminal session and start cruise from there and I use --daemon, but somehow I must make sure I cannot close the terminal window or else the "Source Control Error" will happen again.

Also doing it via SSH is definitely no-no. It has to be in the real machine, and you cannot close the terminal session window even if --daemon suggest you can detached and close the window.. hmms does that make sense. I am confused myself :(

Using XServe Leopard FYI.

It is running fine now as long as I don't close the session :)
