### ISSUE TITLE
Couldn't get a file descriptor referring to the console

### ISSUE THREAD

**Issue by Govinda-Fichtner** [thoughtworks/cruisecontrol.rb#72]
I am not really sure if this is an issue with cruisecontrol.rb, but anyhow I need help...
I am running cruise with passenger for the webfrontend and github as coderepository... the builder in general seems to work and individual builds start and run until the end of the migrations.... then I get the error: Couldn't get a file descriptor referring to the console without any additional information.
Of course the build should continue after the migrations and run all the tests...

Does anybody know what the problem could be?

I am using 
ruby 1.9.2p180
thoughtworks-cruisecontrol.rb-v1.4.0-183-geaba789.tar
passenger 3.0.7
Ubuntu 10.04.3 LTS

**Comment by bguthrie** [comment]
You may have run into your system's limit on the number of open file descriptors, although I couldn't tell you why without knowing a bit more about that box. You can easily increase the limit--Googling around a little bit led me to [this guide](http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/)--or try to figure to figure out why so many are gettng opened--does this box have other responsibilities besides those of a build server?

If you'd like to ask around a bit before opening an issue, there is a [CruiseControl.rb users mailing list](http://rubyforge.org/mailman/listinfo/cruisecontrolrb-users) you can subscribe to.

**Comment by Govinda-Fichtner** [comment]
Hmmm, I don't think so... the server is an ec2 instance which is only used for cruisecontrol.rb... I don't know the exact reason why it fails... but now I know how to get it to run... might be related to running cc.rb with apache/passenger... 
After I changed the cc configuration(site_config.rb) by adding "BuilderStarter.run_builders_at_startup = false" and then starting the builder process manually at the console with "sudo su -c "./cruise builder projectname" www-data" all the builds which are started e.g. with "Build Now" in the GUI, finish as they should without the file descriptor error message...
So there seems to be a difference in how the builder is started from within apache/passenger compared to starting it manually from the command line...
Could there be a problem with "Platform.create_child_process(project_name, command)" if cc is running with apache/passenger?

**Comment by Govinda-Fichtner** [comment]
OK. Found the culprit. It was the cover_me gem trying to open the coverage report in a browser... after configuring the cover_me task like

```
task :report do
   require 'cover_me'
   CoverMe.config do |c|
     c.at_exit = proc {}    # do not open the coverage report automatically
     c.html_formatter.output_path = File.join(ENV['CC_BUILD_ARTIFACTS'] || Rails.root , 'coverage')
   end
   CoverMe.complete!
end
```

everything worked. Sorry for the inconvenience...

**Comment by bguthrie** [comment]
No trouble at all. Glad you were able to figure it out!
