### ISSUE TITLE
Upgrade to Rails 3.2.x

### ISSUE THREAD

**Issue by ealden** [thoughtworks/cruisecontrol.rb#93]
I just checked out CC.rb's code and realized that it is still in 3.0.7.  Are there plans to upgrade to the latest 3.2 release?

**Comment by jdickey** [comment]
It can apparently be updated to 3.0.20 just by editing `cruisecontrol.gemspec`. However, most of the other Gems are also outdated, several egregiously so. Looking at the network graph, it's pretty obvious that lots of people are scratching their own worst itches, but updates to Thoughtworks' master branch have been few. I'm debating between yet another fork-and-scratch-my-own-itches or going with something else.

**Comment by seanmarcia** [comment]
This is on the horizon. Now that I have access I can start pulling in all the great work that people are doing as well as my own. I'm planning on spending some time soon to map things out.

**Comment by synth** [comment]
i just upgraded cruisecontrol to 3.2 successfully, got all tests passing tonight.  having unrelated build issues on my own project so i'm not quite ready for a pull request. but if anyone wants to, they can check out my fork: https://github.com/planetio/cruisecontrol.rb

**Comment by synth** [comment]
One thing that I would like feedback on is that there is a conflict with ActiveSupport's Configuration class.  CruiseControl's Configuration is in the global namespace.  In my fork, I got everything working by scoping the Configuration class underneath the module CruiseControl.  This is fine except for the fact that it is not backwards compatible and will break existing site_config's.  Don't know if there is a better way to solve this...

**Comment by seanmarcia** [comment]
I saw on a couple forks that they've also upgrade to 3.2 and I'm looking to see what their approach was. I'm also unsure how important it is to be backwards compatible at this point... I know the rails core team stated they are not going to support 2.3 going forward and I have to imagine that 3.0 isn't too far off.

**Comment by synth** [comment]
maybe we should continue on to rails 4.0? :)  I've been using my branch consistently now in my CI loop and its pretty solid.  The only thing that potentially needs work is the build failure email has no html formatting at the moment.  If i get more time I'll try to take a look.

**Comment by ajeygore** [comment]
I think if it's worth then let's try to merge the forks
